// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_200 = "CgkI7KnE_d0eEAIQAg"; // <GPGSID>
        public const string achievement_100 = "CgkI7KnE_d0eEAIQBA"; // <GPGSID>
        public const string achievement_1000 = "CgkI7KnE_d0eEAIQCA"; // <GPGSID>
        public const string achievement_buy_sand_ground = "CgkI7KnE_d0eEAIQDQ"; // <GPGSID>
        public const string achievement_buy_a_new_character = "CgkI7KnE_d0eEAIQCQ"; // <GPGSID>
        public const string achievement_buy_ocean_background = "CgkI7KnE_d0eEAIQDA"; // <GPGSID>
        public const string achievement_you_wait_to_long = "CgkI7KnE_d0eEAIQBg"; // <GPGSID>
        public const string leaderboard_score = "CgkI7KnE_d0eEAIQAA"; // <GPGSID>
        public const string achievement_join_the_game = "CgkI7KnE_d0eEAIQAQ"; // <GPGSID>
        public const string achievement_500 = "CgkI7KnE_d0eEAIQBQ"; // <GPGSID>

}

